import '../globals.css'
import { Inter } from 'next/font/google'
import AdminHeader from './component/AdminHeader'
import AdminSide from './component/AdminSide'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Admin',
    description: 'Generated by create next app',
}

export default function Layout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AdminHeader />
                <div className="flex">
                    <div className="w-2/12">
                        <AdminSide />
                    </div>
                    <div className="w-10/12 p-3">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
