import Head from "next/head";
import Footer from './(design)/components/Footer'
import Heade from './(design)/components/Heade'
import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import Side from "./(design)/components/Side";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Online-app',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Script src="https://cdn.tailwindcss.com"></Script>
      <body className={inter.className}>
        <Heade />
        <div className="flex ">
          <div className="w-2/12 bg-slate-200">
            <Side />
          </div>
          <div className="w-10/12 p-6">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}